<?php
    require_once('../include/extension_links.php');
?>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/essay_set_rubric_setting.css">   
    <title></title>
</head>
<body>
        <div class="essay-criteria-setting-container"> 
        <div class="back-arrow-container">
        <a href="AcademAI-Create-Essay.php"><i class="fa-solid fa-arrow-left"></i></a>
        </div>
  

        <div class= "subject-container" >
       
        <!-- Example split danger button -->
<div class="btn-group btn-group-choose-rubric">
  <button type="button" class="btn btn-choose-rubric">Choose Rubric</button>
  <button type="button" class="btn dropdown-choose-rubric-btn dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
    <span class="visually-hidden">Toggle Dropdown</span>
  </button>
  <ul class="dropdown-menu dropdown-choose-rubric">
    <li><a class="dropdown-item" href="#">CC 105</a></li>
    <li><a class="dropdown-item" href="#">NSTP</a></li>
    <li><a class="dropdown-item" href="#">CC 102</a></li>
  </ul>
</div>

        <h1 class="subject-title">CC 104 Information Management</h1>

    
          <div class="criteria-table-container">
            
                    <table class="table table-hover table-bordered">
                        <thead class="criteria-heading" id="criteria-heading">
                            <tr>
                            <th scope="col">Criteria</th>
                        
                            <th scope="col" id="criteria-level-header">
                            <div class="d-flex justify-content-center pt-2">
                            <p class="levels">Advanced<p>
                            </div>                 
                            <div class="d-flex align-items-center justify-content-center py-2">
                                <span class="px-2">100%</span>  
                            </div>
                            </th>
            
                            <th scope="col"id="criteria-level-header">
                            <div class="d-flex justify-content-center pt-2">
                            <p class="levels">Proficient<p>
                            </div> 
                            <div class="d-flex align-items-center justify-content-center py-2">
                                <span class="px-2">75%</span>  
                            </div>
                            </th>
                            <th scope="col"id="criteria-level-header">
                            <div class="d-flex justify-content-center pt-2">
                            <p class="levels">Needs Improvement<p>
                            </div>  
                            <div class="d-flex align-items-center justify-content-center py-2">
                                <span class="px-2">50%</span>  
                            </div>
                            </th>
                            <th scope="col"id="criteria-level-header">
                            <div class="d-flex justify-content-center pt-2">
                            <p class="levels">Warning<p>
                            </div>  
                            <div class="d-flex align-items-center justify-content-center py-2">
                                <span class="px-2">25%</span>  
                            </div>
                            </th>
                          
                            </th>
                            <th scope="col">Weight <span>%</span></th>
                            </tr>
                        </thead>

                        <tbody class="predefined-criteria">
                            <tr>
                            <td>1.AI Generated</td>
                            <td>
                               <p class="rubric-criterion">Little to no evidence of original thought or human input. The content appears to be primarily generated by AI with minimal human intervention. </p>
                            </td>
                            <td>
                            <p class="rubric-criterion">Some evidence of human input, but the majority of the content is generated by AI. Limited originality and creativity are apparent.</p>
                            
                            </td>
                           
                            <td>
                            <p class="rubric-criterion">A balanced mix of AI-generated content and human input. Original thought and creativity are somewhat evident, but reliance on AI is still noticeable.</p>
                            </td>
                            <td>
                            <p class="rubric-criterion"> Predominantly human-generated content with minimal reliance on AI. Originality, creativity, and critical thinking are clearly demonstrated.</p>
                            
                            </td>
                            <td class="rubric-criterion-weight-class">
                            <p class="rubric-criterion-weight"> 15%</p>
                            </td>

                        
                            </tr>
                            <tr>
                            <td>2.Plagiarized</td>
                        
                            <td>
                            <p class="rubric-criterion"> Extensive instances of direct copying from online sources or database repositories without attribution. Little to no original content is present.</p>
                            </td>
                            <td>
                            <p class="rubric-criterion"> Significant portions of the content are directly copied from online sources or database repositories with minimal attempt to disguise plagiarism.</p>
                            </td>
                           
                            <td>
                            <p class="rubric-criterion">Some instances of copied content from online sources or database repositories, but with some effort made to paraphrase or rephrase. Limited original content is present.</p>
                            </td>
                            <td>
                            <p class="rubric-criterion">No evidence of direct copying from online sources or database repositories. All content is original or properly attributed.</p>
                            </td>
                            <td class="rubric-criterion-weight-class">
                            <p class="rubric-criterion-weight"> 15%</p>
                            </td>

             


                          
                    

                            </tr>



                            <tr>
                            <td>3.Focus on Topic(Content)</td>
                            <td>
                               <p class="rubric-criterion">There is clear. well focused topic. The main idea stands out and is supported by detailed information.</p>
                            </td>
                            <td>
                            <p class="rubric-criterion">The main idea is clear, but the supporting. information is general</p>
                            </td>
                           
                            <td>
                            <p class="rubric-criterion">The main idea is somewhat clear.</p> 
                            </td>

                            <td>
                            <p class="rubric-criterion">The main idea is not clear. There is a seemingly random collection of information.</p>   
                            </td>
                        
                            <td class="rubric-criterion-weight-class">
                            <p class="rubric-criterion-weight"> 40%</p>
                            </td>

                            </tr>

                            
                            <tr>
                            <td>4.Sequencing (Organization)</td>
                            <td>
                               <p class="rubric-criterion">Details are placed in a logical order and the way they are presented effectively keeps the interest of the reader.</p>
                            </td>
                            <td>
                            <p class="rubric-criterion">Details are placed in a logical order, but the way they are presented/introduced sometimes makes the writing less interesting.  </p>                     
                            </p>                     
                            </td>                          
                            <td>
                            <p class="rubric-criterion">Some details are not in a logical or expected order, and this distracts the reader.</p>
                            </td>
                            <td>
                            <p class="rubric-criterion">Many details are not in a logical or expected order.There is little sense that the writing is organized. 
                            </td>
                            <td class="rubric-criterion-weight-class">
                            <p class="rubric-criterion-weight"> 10%</p>
                            </td>

                            </tr>

                            
                            <tr>
                            <td>5.Command of Evidence</td>
                            <td>
                               <p class="rubric-criterion">The 	writer successfully uses several reasons/ appeals to try to show why the reader should care or want to know more about the topic.</p>
                            </td>
                            <td>
                            <p class="rubric-criterion">The writer successfully uses one or two reasons/appeals to try to show why the reader should care or want to know more about the topic.</p>                           
                            
                            </td>
                           
                            <td>
                            <p class="rubric-criterion">The writer attempts to make the reader care about the topic but is not really successful.</p>
                            </td>

                            <td>
                            <p class="rubric-criterion">The writer makes no attempt to make the reader care about the topic.</p>
                            </td>
                   
                            <td class="rubric-criterion-weight-class">
                            <p class="rubric-criterion-weight"> 5%</p>
                            </td>
                            </tr>

                            
                            <tr>
                            <td>6.Word Choice</td>
                            <td>
                               <p class="rubric-criterion">The writer uses vivid words and phrases that linger or draw pictures in the reader's mind, and the choice and placement of the word seems accurate and natural.</p>
                            </td>
                            <td>
                            <p class="rubric-criterion">The writer uses vivid words and phrases that linger or draw pictures in the reader's mind, but occasionally the words are used Inaccurately or seem overdone.</p>
                            
                            </td>
                           
                            <td>
                            <p class="rubric-criterion">The writer uses words that communicate clearly, but the writing lacks variety, punch, or flair.</p>
                            </td>
                            <td>
                            <p class="rubric-criterion">The writer uses a limited vocabulary that does not communicate strongly or capture the reader's interest. Jargon or clichés may be present and detract from the meaning. </p>
                            
                            </td>
                            <td class="rubric-criterion-weight-class">
                            <p class="rubric-criterion-weight"> 5%</p>
                            </td>

                            </tr>
                            
                            <tr>
                            <td>7.Sentence Structure (Sentence Fluency)</td>
                            <td>
                               <p class="rubric-criterion">All sentences are well-constructed with varied structured. </p>
                            </td>
                            <td>
                            <p class="rubric-criterion">Most sentences are well constructed with varied structure.</p>
                            </td>
                           
                            <td>
                            <p class="rubric-criterion">Most sentences are well-constructed but have a 	similar structure. </p>      
                            </td>
                            <td>
                            <p class="rubric-criterion">Sentences lack structure and appear incomplete or rambling. </p>     
                             
                           </td>
                           <td class="rubric-criterion-weight-class">
                            <p class="rubric-criterion-weight"> 5%</p>
                            </td>

                            </tr>
                            <tr>
                            <td>8.Grammar and Spelling (Conventions)</td>
                            <td>
                               <p class="rubric-criterion">The writer makes no errors in grammar or spelling, showing strong command of language. </p>
                            </td>
                            <td>
                            <p class="rubric-criterion">The writer makes occasional errors in grammar or spelling showing some command of language. </p>
                            </td>
                           
                            <td>
                            <p class="rubric-criterion">The writer makes some errors in grammar or spelling,showing minimal command of language. </p>      
                            </td>
                            <td>
                            <p class="rubric-criterion">The writer makes many errors in grammar of spelling, showing little command of language. </p>    
                             
                           </td>
                           <td class="rubric-criterion-weight-class">
                            <p class="rubric-criterion-weight"> 5%</p>
                            </td>

                            </tr>
                        </tbody>
                        </table> 


                    </div>       
                </div>
             </div>
            </div>
        </div>


  </div>
</div>  
        
    </div>

    



     <!-- Scripts -->
     <script src="../js/essay_rubric_setting.js"></script>
  


</body>
</html>