<?php
    require_once('../include/extension_links.php');
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/assessment.css">   
    <title></title>
</head>
<body>

<div class="asess">
<div class="back-arrow-section">
<a href="AcademAI-user(learners)-view-quiz-answer-1.php">
    <i class="fa-solid fa-arrow-left" style="color:#9EC8B9;"></i>
    </a>
</div>   

   <div class="essay-criteria-setting-container"> 
       
  
        <div class="criteria-table-container">
                    <table class="table table-hover table-bordered">
                        <thead class="criteria-heading" id="criteria-heading">
                            <tr>
                            <th scope="col">Criteria</th>
                        
                            <th scope="col" id="criteria-level-header">
                            <div class="d-flex justify-content-center pt-2">
                            <p class="levels">Advanced<p>
                            </div>                 
                            <div class="d-flex align-items-center justify-content-center py-2">
                                <span class="px-2">100%</span>  
                            </div>
                            </th>
            
                            <th scope="col"id="criteria-level-header">
                            <div class="d-flex justify-content-center pt-2">
                            <p class="levels">Proficient<p>
                            </div> 
                            <div class="d-flex align-items-center justify-content-center py-2">
                                <span class="px-2">75%</span>  
                            </div>
                            </th>
                            <th scope="col"id="criteria-level-header">
                            <div class="d-flex justify-content-center pt-2">
                            <p class="levels">Needs Improvement<p>
                            </div>  
                            <div class="d-flex align-items-center justify-content-center py-2">
                                <span class="px-2">50%</span>  
                            </div>
                            </th>
                            <th scope="col"id="criteria-level-header">
                            <div class="d-flex justify-content-center pt-2">
                            <p class="levels">Warning<p>
                            </div>  
                            <div class="d-flex align-items-center justify-content-center py-2">
                                <span class="px-2">25%</span>  
                            </div>
                            </th>
                          
                            </th>
                            <th scope="col">Weight <span>%</span></th>
                            <th scope="col">Score <span>%</span></th>
                            </tr>
                        </thead>

                        <tbody class="predefined-criteria">
                            <tr>
                            <td>1.AI Generated</td>
                            <td>
                               <p class="rubric-criterion">Little to no evidence of original thought or human input. The content appears to be primarily generated by AI with minimal human intervention. </p>
                            </td>
                            <td>
                            <p class="rubric-criterion">Some evidence of human input, but the majority of the content is generated by AI. Limited originality and creativity are apparent.</p>
                            
                            </td>
                           
                            <td>
                            <p class="rubric-criterion">A balanced mix of AI-generated content and human input. Original thought and creativity are somewhat evident, but reliance on AI is still noticeable.</p>
                            </td>
                            <td>
                            <p class="rubric-criterion"> Predominantly human-generated content with minimal reliance on AI. Originality, creativity, and critical thinking are clearly demonstrated.</p>
                            
                            </td>
                            <td class="rubric-criterion-weight-class">
                            <p class="rubric-criterion-weight"> 15%</p>
                            </td>

                            <td class="rubric-criterion-weight-class">
                            <p class="rubric-criterion-weight"> 10%</p>
                            </td>

                            

                    
                            </tr>
                            <tr>
                            <td>2.Plagiarized</td>
                        
                            <td>
                            <p class="rubric-criterion"> Extensive instances of direct copying from online sources or database repositories without attribution. Little to no original content is present.</p>
                            </td>
                            <td>
                            <p class="rubric-criterion"> Significant portions of the content are directly copied from online sources or database repositories with minimal attempt to disguise plagiarism.</p>
                            </td>
                           
                            <td>
                            <p class="rubric-criterion">Some instances of copied content from online sources or database repositories, but with some effort made to paraphrase or rephrase. Limited original content is present.</p>
                            </td>
                            <td>
                            <p class="rubric-criterion">No evidence of direct copying from online sources or database repositories. All content is original or properly attributed.</p>
                            </td>
                            <td class="rubric-criterion-weight-class">
                            <p class="rubric-criterion-weight"> 15%</p>
                            </td>
                            
                            <td class="rubric-criterion-weight-class">
                            <p class="rubric-criterion-weight"> 10%</p>
                            </td>

                            </tr>



                            <tr>
                            <td>3.Focus on Topic(Content)</td>
                            <td>
                               <p class="rubric-criterion">There is clear. well focused topic. The main idea stands out and is supported by detailed information.</p>
                            </td>
                            <td>
                            <p class="rubric-criterion">The main idea is clear, but the supporting. information is general</p>
                            
                            </td>
                           
                            <td>
                            <p class="rubric-criterion">The main idea is somewhat clear.</p>   
                            </td>

                            <td>
                            <p class="rubric-criterion">The main idea is not clear. There is a seemingly random collection of information.</p>   
                            </td>
                        
                            <td class="rubric-criterion-weight-class">
                            <p class="rubric-criterion-weight"> 40%</p>
                            </td>
                            <td class="rubric-criterion-weight-class">
                            <p class="rubric-criterion-weight"> 30%</p>
                            </td>

                            </tr>

                            
                            <tr>
                            <td>4.Sequencing (Organization)</td>
                            <td>
                               <p class="rubric-criterion">Details are placed in a logical order and the way they are presented effectively keeps the interest of the reader.</p>
                            </td>
                            <td>
                            <p class="rubric-criterion">Details are placed in a logical order, but the way they are presented/introduced sometimes makes the writing less interesting.</p>                     
                            </td>                          
                            <td>
                            <p class="rubric-criterion">Some details are not in a logical or expected order, and this distracts the reader.</p>
                            </td>
                            <td>
                            <p class="rubric-criterion">Many details are not in a logical or expected order.There is little sense that the writing is organized.</p>
                            </td>
                            <td class="rubric-criterion-weight-class">
                            <p class="rubric-criterion-weight"> 10%</p>
                            </td>
                            <td class="rubric-criterion-weight-class">
                            <p class="rubric-criterion-weight"> 5%</p>
                            </td>

                            </tr>

                            
                            <tr>
                            <td>5.Commitment (Voice)</td>
                            <td>
                               <p class="rubric-criterion">The 	writer successfully uses several reasons/ appeals to try to show why the reader should care or want to know more about the topic.</p>
                            </td>
                            <td>
                            <p class="rubric-criterion">The writer successfully uses one or two reasons/appeals to try to show why the reader should care or want to know more about the topic.</p>                        
                            
                            </td>
                           
                            <td>
                            <p class="rubric-criterion">The writer attempts to make the reader care about the topic but is not really successful.</p>
                            </td>

                            <td>
                            <p class="rubric-criterion">The writer makes no attempt to make the reader care about the topic.</p>
                            </td>
                   
                            <td class="rubric-criterion-weight-class">
                            <p class="rubric-criterion-weight"> 5%</p>
                            </td>

                            <td class="rubric-criterion-weight-class">
                            <p class="rubric-criterion-weight"> 5%</p>
                            </td>

                    
                            </tr>

                            
                            <tr>
                            <td>6.Word Choice</td>
                            <td>
                               <p class="rubric-criterion">The writer uses vivid words and phrases that linger or draw pictures in the reader's mind, and the choice and placement of the word seems accurate and natural.</p>
                            </td>
                            <td>
                            <p class="rubric-criterion">The writer uses vivid words and phrases that linger or draw pictures in the reader's mind, but occasionally the words are used Inaccurately or seem overdone.</p>
                            
                            
                            </td>
                           
                            <td>
                            <p class="rubric-criterion">The writer uses words that communicate clearly, but the writing lacks variety, punch, or flair.</p>
                            </td>
                            <td>
                            <p class="rubric-criterion">The writer uses a limited vocabulary that does not communicate strongly or capture the reader's interest. Jargon or clichés may be present and detract from the meaning. </p>
                            
                            
                            </td>
                            <td class="rubric-criterion-weight-class">
                            <p class="rubric-criterion-weight"> 5%</p>
                            </td>

                            </td>
                            <td class="rubric-criterion-weight-class">
                            <p class="rubric-criterion-weight"> 3%</p>
                            </td>


                          
                            </tr>
                            
                            <tr>
                            <td>7.Sentence Structure (Sentence Fluency)</td>
                            <td>
                               <p class="rubric-criterion">All sentences are well-constructed with varied structured. </p>
                            </td>
                            <td>
                            <p class="rubric-criterion">Most sentences are well constructed with varied structure.</p>
                            </td>
                           
                            <td>
                            <p class="rubric-criterion">Most sentences are well-constructed but have a 	similar structure. </p>      
                            </td>
                            <td>
                            <p class="rubric-criterion">Sentences lack structure and appear incomplete or rambling. </p>      
                             
                           </td>
                           <td class="rubric-criterion-weight-class">
                            <p class="rubric-criterion-weight"> 5%</p>
                            </td>

                            </td>
                           <td class="rubric-criterion-weight-class">
                            <p class="rubric-criterion-weight"> 5%</p>
                            </td>

                           
                            </tr>
                            <tr>
                            <td>8.Grammar and Spelling (Conventions)</td>
                            <td>
                               <p class="rubric-criterion">The writer makes no errors in grammar or spelling, showing strong command of language. </p>
                            </td>
                            <td>
                            <p class="rubric-criterion">The writer makes occasional errors in grammar or spelling showing some command of language. </p>
                            </td>
                           
                            <td>
                            <p class="rubric-criterion">The writer makes some errors in grammar or spelling,showing minimal command of language. </p>      
                            </td>
                            <td>
                            <p class="rubric-criterion">The writer makes many errors in grammar of spelling, showing little command of language. </p>      
                             
                           </td>
                           <td class="rubric-criterion-weight-class">
                            <p class="rubric-criterion-weight"> 5%</p>
                            </td>

                            </td>
                           <td class="rubric-criterion-weight-class">
                            <p class="rubric-criterion-weight"> 5%</p>
                            </td>


                           
                            </tr>
                        </tbody>
                        </table>    
                </div>
           
             <div class="edibtn-score mt-4" >
             <a href="#">
                            <button type="button" class="edit-criteria-btn">Edit Score</button>
                         </a>
            </div>

            </div>
        </div>
  
    </div>
   <div class="feed-container">
    <div class="feedback-container">

        <div class="assessment">
            <h1>System Assessment</h1>
            <div class="assessment-details">
                <div class="asset">
                <P class="rubrics">Focus on Topic (Content)(40%):30%</p> 
                <P class="rubrics-explanation"> Impressive performance! Your content is highly relevant, thorough, and accurate, demonstrating a deep understanding of the topic. Exceptional work!
                </p>   
                </div>
            </div>

            <div class="assessment-details">
                <div class="asset">
                <P class="rubrics">Sequencing (Organization)(10%): 10%</p> 
                <P class="rubrics-explanation">Well done! Your essay is excellently organized, with a clear and logical progression of ideas. Transitions are seamless, enhancing overall coherence. Great job!
                </p>   
                </div>
            </div>
          
            <div class="assessment-details">
                <div class="asset">
                <P class="rubrics">Commitment (Voice)(5%): 3%</p> 
                <P class="rubrics-explanation">Good effort in maintaining a consistent voice throughout the essay. Work on further developing your unique writing style to enhance engagement.
                </p>   
                </div>
            </div>

            <div class="assessment-details">
                <div class="asset">
                <P class="rubrics">Word Choice (5%): 3%</p> 
                <P class="rubrics-explanation">Your choice of words effectively communicates your ideas. Continue to expand your vocabulary to add depth and nuance to your writing.
                </p>   
                </div>
            </div>

            <div class="assessment-details">
                <div class="asset">
                <P class="rubrics">Sentence Structure (Sentence Fluency) (5%): 2%</p> 
                <P class="rubrics-explanation">Your sentences flow well, contributing to the overall coherence of the essay. Consider varying sentence structures to maintain reader interest.
                </p>   
                </div>
            </div>

            <div class="assessment-details">
                <div class="asset">
                <P class="rubrics">Grammar and Spelling (Conventions) (5%): 2%</p> 
                <P class="rubrics-explanation">Your essay demonstrates a good grasp of grammar and spelling conventions. Pay attention to detail to minimize errors and enhance readability.
                </p>   
                </div>
</div>

        </div>
        <div class="assessment">
            <h1>AI Report</h1>
            <div class="assessment-details-ai">
               <P class="rubrics-ai">AI Generated (15%): 10%</p>
                <P  class="rubrics-ai-explanation">Your work shows a high probability of AI intervention.<p>   
            </div>
        </div>
        <div class="assessment">
            <h1>Plagiarism Report</h1>
            <div class="assessment-details-plagiarize">
               <P class="rubrics-plagiariaze">Plagiarize(10%): 5%
                <p class="plagiarized-works-database">You have copied a portion of your work from the following online sources, 
                comprising 50% of your content.</p>
                <p class="plagiarized-works-1">1.https://www.ide.go.jp/English/Research/Project/2021/2021240005.html</p>
                <p class="plagiarized-works-1">2.https://edition.cnn.com/videos/world/2024/03/25/starlink-russia-ukraine-musk-npw-pkg-ebof-vpx.cnn</p>
                <p class="plagiarized-works-1">3.https://edition.cnn.com/2024/03/25/travel/china-south-east-asia-travel-train-infrastructure-intl-hnk/index.html</p>
                <p class="plagiarized-works-database">You have copied a portion of your work from these subsequent individuals, 
                comprising 50% of your content.</p>
                <p class="plagiarized-works">1.Dela Cruz, Maxine A.</p>
                <p class="plagiarized-works">2.Infante,Catrina A.</p>
            </div>
            </div>  
     
           <div class="professor-comment">
            <div>
            <label for="comment">Provide Feedback</label>
            <textarea id="comment" name="comment" rows="5" required></textarea>
            <div class="btn-for-feedback">
                <button type="submit" class="submit-btn-comment">Send</button>
            </div>
            </div>
</div>
    </div>
    
</div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
        document.querySelector('.feedback-container').classList.add('show');
        document.querySelectorAll('.assessment, .comments').forEach(function(el) {
            el.classList.add('show');
        });
    });
</script>
</body>
</html>